import type { NextPage } from "next";
import Head from "next/head";

const AdminDashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        {/* <meta http-equiv="refresh" content="2"></meta> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Admin page</h1>
    </div>
  );
};

export default AdminDashboard;
