import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import SliderComp from "../components/user/slider/slider";
import FeaturesComp from "../components/user/features/features";
import NewFoods from "../components/user/newFoods/newFoods";
import Menu1 from "../components/user/newFoods/menu1/menu1";
import Menu2 from "../components/user/menu2/menu2";
import { render } from "react-dom";
const Home: NextPage = () => {
  // const handleUpload = (e: any) => {
  //   const file = e.target.files[0];
  //   const formData = new FormData();
  //   formData.append("file", file);

  //   axios({
  //     method: "POST",
  //     url: "/api/uploads",
  //     headers: {
  //       "Content-Type": "multi-part",
  //     },
  //     data: formData,
  //   });
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderComp />
      <FeaturesComp />
      <Menu1 />
      <Menu2 />
      <NewFoods />
    </div>
  );
};

export default Home;
